// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.
/* eslint-disable @typescript-eslint/no-empty-object-type */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Add your tables here
    }
    Views: {
      // Add your views here
    }
    Functions: {
      // Add your functions here
    }
    Enums: {
      // Add your enums here
    }
    CompositeTypes: {
      // Add your composite types here
    }
  }
}

// Project reference: e54bda36-4533-482b-aea1-99876851c28b
// Last updated: 2026-04-06T14:48:44.578286
